agqr_stream_url: https://www.uniqueradio.jp/agplayer5/hls/mbr-ff.m3u8
format: mp3
schedules:
  - title: "テスト"
    identifier: "test"
    weekday: Sun
    time: "20:55"
    length_minutes: 1
    thumb_file_name: "default.png"
    artist_name: "artist"
